apiVersion: batch/v1
kind: CronJob
metadata:
  name: disk-cleanup-job
  namespace: blockchain-ml
spec:
  # Run daily at 2 AM
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: default
          restartPolicy: OnFailure
          containers:
          - name: cleanup
            image: blockchain-ml-backend:latest
            imagePullPolicy: Never
            command: ["python", "cleanup_disk.py", "--cleanup-now", "--threshold", "20"]
            resources:
              requests:
                cpu: "250m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
            securityContext:
              runAsUser: 0  # Run as root for system operations
---
apiVersion: batch/v1
kind: Job
metadata:
  name: disk-cleanup-immediate
  namespace: blockchain-ml
spec:
  template:
    spec:
      serviceAccountName: default
      restartPolicy: Never
      containers:
      - name: cleanup
        image: blockchain-ml-backend:latest
        imagePullPolicy: Never
        command: ["python", "cleanup_disk.py", "--cleanup-now"]
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        securityContext:
          runAsUser: 0
